# =============================================================
# Bitcoin Core Configuration — OmniNode
# =============================================================

# Network
testnet=1

# Global
server=1
printtoconsole=1
debug=0

# Testnet-specific settings
[test]
rpcuser=omninode_btc
rpcpassword=OmniNode@2025!
rpcport=8332
rpcbind=0.0.0.0
rpcallowip=127.0.0.1
rpcallowip=172.16.0.0/12
port=8333
dbcache=512
maxmempool=300
maxconnections=25
prune=550
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
